#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: true
  identity:
    hostname: {{ host_name }}
    password: $6$RrnTz0.kdqNtRgLq$2KjPXoM.V985GqUdqqigdMhxv3K0bkcxdG6Lm5l5xQLM.K5e5SaIL/S8Q5ghGX6vO/VhoVCfqOOJ6g8JUz5bt.
    realname: Generic
    username: ubuntu_user
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    toggle: null
    variant: ''
    layout-options: ['en_US', 'de']
  locale: en_US.UTF-8
  network:
    version: 2
    wifis:
      wlp0s20f3:
        access-points:
          Neelam_wifi5:
            auth:
              key-management: psk
              password: DANCINGonmyown@1234
            networkmanager:
              name: Neelam_wifi5
              passthrough:
                ipv6.addr-gen-mode: default
                ipv6.ip6-privacy: '-1'
                proxy._: ''
                wifi-security.auth-alg: open
              uuid: ad6bb455-df75-421d-bbe4-92742641e075
        dhcp4: true
        dhcp6: true
        networkmanager:
          name: Neelam_wifi5
          uuid: ad6bb455-df75-421d-bbe4-92742641e075
        renderer: NetworkManager
  oem:
    install: auto
  source:
    id: ubuntu-desktop-minimal
    search_drivers: true
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: false
  storage:
    config:
    - transport: pcie
      preserve: true
      id: nvme-controller-nvme0
      type: nvme_controller
    - ptable: gpt
      serial: MTFDHBA512QFD-1AX1AABHA_UJXEC0170F4L81_1
      wwn: eui.000000000000000100a075212e963444
      nvme_controller: nvme-controller-nvme0
      path: /dev/nvme0n1
      preserve: true
      name: ''
      grub_device: false
      id: disk-nvme0n1
      type: disk
    - device: disk-nvme0n1
      size: 209715200
      flag: boot
      number: 1
      preserve: true
      grub_device: true
      offset: 1048576
      partition_type: c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      path: /dev/nvme0n1p1
      uuid: 65b5342a-c4c7-421c-be03-6b6be4747d8e
      id: partition-nvme0n1p1
      type: partition
    - device: disk-nvme0n1
      size: 16777216
      flag: msftres
      number: 2
      preserve: true
      grub_device: false
      offset: 210763776
      partition_type: e3c9e316-0b5c-4db8-817d-f92df00215ae
      path: /dev/nvme0n1p2
      uuid: 1b3d3c5e-919f-474b-beb5-e0df0002a40e
      id: partition-nvme0n1p2
      type: partition
    - device: disk-nvme0n1
      size: 255555796992
      number: 3
      preserve: true
      grub_device: false
      offset: 227540992
      partition_type: ebd0a0a2-b9e5-4433-87c0-68b6b72699c7
      path: /dev/nvme0n1p3
      uuid: 8a8cec95-4ec3-4a44-a887-5544f63d78dd
      id: partition-nvme0n1p3
      type: partition
    - device: disk-nvme0n1
      size: 770703360
      number: 4
      preserve: true
      grub_device: false
      offset: 511338086400
      partition_type: de94bba4-06d1-4d40-a16a-bfd50179d6ac
      path: /dev/nvme0n1p4
      uuid: ca5f950c-9955-4bec-8337-b436bcebdc40
      id: partition-nvme0n1p4
      type: partition
    - device: disk-nvme0n1
      size: 202194812928
      flag: linux
      number: 5
      preserve: true
      grub_device: false
      offset: 255783337984
      resize: true
      partition_type: 0fc63daf-8483-4772-8e79-3d69d8477de4
      path: /dev/nvme0n1p5
      uuid: 63e1d3d9-94f0-4995-bb42-ee15ebd2f1dc
      id: partition-nvme0n1p5
      type: partition
    - device: disk-nvme0n1
      size: 53359935488
      wipe: superblock
      number: 6
      preserve: false
      offset: 457978150912
      path: /dev/nvme0n1p6
      id: partition-0
      type: partition
    - fstype: ext4
      volume: partition-0
      preserve: false
      id: format-0
      type: format
    - path: /
      device: format-0
      id: mount-1
      type: mount
    - fstype: vfat
      volume: partition-nvme0n1p1
      preserve: true
      id: format-partition-nvme0n1p1
      type: format
    - path: /boot/efi
      device: format-partition-nvme0n1p1
      id: mount-0
      type: mount
  timezone: Europe/Berlin
  updates: security
  version: 1